### ISSUE TITLE
Put mixins methods in the component prototype

### ISSUE THREAD

**Issue by mquandalle** [peerlibrary/meteor-blaze-components#34] opened 2015-04-24 10:11 UTC
Imagine that I define a `openable` mixin with a few methods on it (`open()`, `close()`, `toogle()`, and `isOpen()`). I then use this mixin in a UI component.

In the body of this component methods I find it very unatural to call `this.callFirstWith(this, 'open');` where what I simply want to express is `this.open()`. Maybe the `mixins` functions could put mixins methods directly on the parent component?

This would be similar to how React does it:

``` jsx
var SetIntervalMixin = {
  componentWillMount: function() {
    this.intervals = [];
  },
  setInterval: function() {
    this.intervals.push(setInterval.apply(null, arguments));
  },
  componentWillUnmount: function() {
    this.intervals.map(clearInterval);
  }
};

var TickTock = React.createClass({
  mixins: [SetIntervalMixin], // Use the mixin
  getInitialState: function() {
    return {seconds: 0};
  },
  componentDidMount: function() {
    this.setInterval(this.tick, 1000); // Call a method on the mixin
  },
  tick: function() {
    this.setState({seconds: this.state.seconds + 1});
  },
  render: function() {
    return (
      <p>
        React has been running for {this.state.seconds} seconds.
      </p>
    );
  }
});
```

**Comment by mitar** [comment] 2015-04-24 10:24
You are free to do that using some other mixin approach. For example, how it is described [here for CoffeeScript](https://arcturo.github.io/library/coffeescript/03_classes.html).

Often this can be simply `_.extend MyComponent::, mixin`.

The design goals with mixins provided by Blaze Components were that such official monkey-patching is not scalable for larger codebases and thus should be avoided. Modifying prototype under the hood can lead to namespace collisions. Imagine that you add a mixin which overrides one of your existing methods. How you know that? How you make it so that both of those methods (on component and in the mixin) are called? How you define which one is called first? Or what if you want only one to be called?

So just overriding brings issues because you do not have control here and composition works only for small examples.

But nothing prevents you from using such approach in your code or offering such mixins to the public. I just do not believe it is a good practice.

You could even use BlazeComponents mixins to do that:

``` coffee
FooBarMixin extends BlazeComponent
  mixinParent: (mixinParent) ->
    @extendMixinParent mixinParent if mixinParent
    super

  extendMixinParent: (mixinParent) ->
    # This does not modify the prototype, but extends the instance itself.
    _.extend mixinParent,
      foo: @foo
      bar: @bar
```

Anyway, this is probably a duplicate of #11. So I am closing it as a duplicate. In #11 you have a bit more of discussion on this topic and rationale for current design.

**Comment by mitar** [comment] 2015-04-24 10:26
You could define and publish a `OverrideMixinParentMixin` which would provide an extension point for other mixins to provide methods which should be added to the mixin component instance. ;-)

**Comment by mitar** [comment] 2015-04-24 10:31
``` coffee
OverrideMixinParentMixin extends BlazeComponent
  mixinParent: (mixinParent) ->
    @extendMixinParent mixinParent if mixinParent
    super

  extendMixinParent: (mixinParent) ->
    # This does not modify the prototype, but extends the instance itself.
    _.extend mixinParent, mixinParent.callFirstWith mixinParent, 'mixinParentMethods'

FooBarMixin extends BlazeComponent
  mixinParentMethods: ->
    _.extend @mixinParent().callFirstWith(@, 'mixinParentMethods'),
      foo: @foo
      bar: @bar

FooBarComponent extends BlazeComponent
  mixins: ->
    [FooBarMixin, OverrideMixinParentMixin]
```

**Comment by mquandalle** [comment] 2015-04-24 10:44
Thank you for the fast answer @mitar :-)

I sure can define my own inheritance model to make the desired API work. But this thread was more about making it the default.

You claim that this approach is not suitable for complex components. Implementation aside, if `this.method(arg)` behaves exactly like `this.callFirstWith(this, 'method', arg)`, would that still introduces some ambiguity about which method we call? I feel that the react model is more intuitive to use.

**Comment by mitar** [comment] 2015-04-24 10:56
So I worry about clobbering the namespace of the component.

Another problem is, that `this.method` cannot call `this.callFirstWith(this, 'method', arg)` anymore to call on, if mixin API would copy stuff and not have things like `callFirstWith`.

Or, are you saying that what we could do is leave `callFirstWith` API as it is, but simply do that all methods which do not override anything on the component are automatically copied over, just in case you want to use them directly? This is an interesting idea. So in some way, semantically, for union of all methods defined by all mixins you would define a default implementation which would be `this.callFirstWith(this, 'method', args...)`.

The issue is that binding to `this` might not work then. Because the code in mixin expect `this` to be bound to the mixin, not to the component. By having explicit API like `OverrideMixinParentMixin` provides would allow you to know that methods defined under `mixinParentMethods` will be called with bound to the component.

One option would be that while copying the methods to the component from a mixin, we would `_.bind` them to the component instance. So that even if they are on the component, they would be called on the mixin. But this is a bit hard to reason about. But it would also make `callFirstWith` work as expected. In fact, it would make mixin do not care about if a method was copied over to the component. Copying over to the component of methods would be something a component developer would decide.

About official way. I do think that at some point we (as a community) should offer a set of semi-official mixins. For example, until now we have two such proposals:
- a mixin to set methods on the component (which can implement any of the above semantics I described, binding `this` and the rest)
- a mixin which allows one to easily replace the template a component is using, without having to extend it (see #26 and [#25](https://github.com/peerlibrary/meteor-blaze-components/issues/25#issuecomment-94958384))

Maybe for the second thing we should go differently. Maybe the component developer should be able to specify which of mixins' methods should be "lifted" to the component directly. So not that mixins add them. But you as a developer specify that. (Of course mixins could provide some default suggested set or something.)

Anyway, I do not think that this should be in core, because we can use develop it using existing codebase. But I do think that it would be interesting and useful to have such mixins and allow people to experiment with them.

**Comment by mitar** [comment] 2015-04-24 11:03
BTW, React does not provide mixins with [ES6 classes](https://facebook.github.io/react/docs/reusable-components.html#no-mixins).

For me this feels like syntactic sugar a bit. So instead of calling a bit verbose `this.callFirstWith(this, 'setInterval', this.tick, 1000)` you would prefer `this.setInterval(this.tick, 1000)` with the same semantics?

So for me `callFirstWith` is similar to `super`. Imagine that you are doing in inheritance something like `super.setInterval(this.tick, 1000)` (ES6 syntax). Just that you are moving side-ways, along mixins.

But I agree it is a bit verbose.

**Comment by offthegrass** [comment] 2015-04-24 11:57
[#3](https://github.com/peerlibrary/meteor-blaze-components/issues/3)

**Comment by mitar** [comment] 2015-04-24 23:11
Reopening to have a bit more discussion.

**Comment by mquandalle** [comment] 2015-04-25 19:07
In a way we could consider that the whole composition thing (here “mixin”) is not the responsibility of the blaze-component lib, but instead something the language object model should handle. It's a bit sad that ES6 doesn't provide anything in this regard (traits, generics, interfaces, mixins...), and it seems to be the reason why Facebook doesn't provide mixins support in their React for ES6.

One solution would be to switch to a language that compiles to JavaScript and supports this kind of object composition, like Typescript (and ClojureScript?). But it seems very unlikely most users will switch to these languages soon, especially in the specific meteor ecosystem. Maybe the babeljs ecosystem will provide a solution to the composition/multiple inheritance problem in a reasonable time-scale?

The other solution, the one you started to take with blaze-component, is to handle this composition feature yourself, even if in a ideal world that wouldn't be your role. What I had in mind is what you have described in https://github.com/peerlibrary/meteor-blaze-components/issues/34#issuecomment-95893136, that is copying mixin methods that do not conflict with the existing component methods. The goal is only to provide an intuitive and clean composition API, not to provide anything that wasn't previously possible. Basically instead of figuring out which method to call at `callFirstWith` call time, you do it when the `mixins` definition is executed.

I'm still not sure if we should distinguish between the `this` of the mixin and of the component, aren't they the same thing? If they are, we can simply use `_.bind(this)` as you suggested.

Here is an example of the desired usage:

``` js
OpenableMixin = BlazeComponent.extendComponent({
  onCreated: function() {
    this._isOpen = new ReactiveVar(false);
  },

  open: function() {
    this._isOpen.set(true);
  },

  close: function() {
    this._isOpen.set(false);
  },

  toogle: function() {
    this._isOpen.set(! this._isOpen.get());
  },

  isOpen: function() {
    return this._isOpen.get();
  }
});

BlazeComponent.extendComponent({
  template: function() {
    return 'addMessageComponent';
  },

  mixins: function() {
    return [OpenableMixin];
  },

  sendMessage: function() {
    // component method, do something
    this.close();
  },

  events: function() {
    return [{
      'click .js-open-form': this.open,
      'submit': this.sendMessage
    }];
  }
}).register('addMessageComponent');
```

(Sorry it's JavaScript, not CoffeeScript. I also like coffee but I'm currently using blaze-components for the LibreBoard application, which is written in JavaScript :-))

**Comment by mitar** [comment] 2015-04-25 20:17
> I'm still not sure if we should distinguish between the this of the mixin and of the component, aren't they the same thing? If they are, we can simply use _.bind(this) as you suggested.

No, they are not the same thing. Component and mixins have each their own instance. With this they get their own namespace and state. For me, this is important because I prefer explicit extension points over "magical" one. So in some way each mixin can expose public API, but also have internal stuff others should not touch. You cannot really hide this in JavaScript, but you can for example use `_` as a prefix or something to signal this. For example, in the way you use `_isOpen` in your mixin. The point is, I do not want two mixins to clash and store variable with the same name onto the component.

So, I understand your example, but I think it introduces possible conflicts just for the expense of not writing a bit more verbose code. Is it really worth it?

``` javascript
OpenableMixin = BlazeComponent.extendComponent({
  onCreated: function() {
    this._isOpen = new ReactiveVar(false);
  },

  open: function() {
    this._isOpen.set(true);
  },

  close: function() {
    this._isOpen.set(false);
  },

  toogle: function() {
    this._isOpen.set(! this._isOpen.get());
  },

  isOpen: function() {
    return this._isOpen.get();
  }
});

BlazeComponent.extendComponent({
  template: function() {
    return 'addMessageComponent';
  },

  mixins: function() {
    return [OpenableMixin];
  },

  sendMessage: function() {
    // component method, do something
    this.callFirstWith(this, 'close');
  },

  open: function() {
    this.callFirstWith(this, 'open');
  },

  events: function() {
    return [{
      'click .js-open-form': this.open,
      'submit': this.sendMessage
    }];
  }
}).register('addMessageComponent');
```

Is this really so much worse?

**Comment by mquandalle** [comment] 2015-04-25 20:49
This is what I do today, so there is nothing insurmountable with this API, but it still makes things more complicated that they could be. First I have to remember the `callFirstWith` method name and arguments, passing the name of a function as the second parameter is something we don't do anywhere else. It also makes extracting some methods of a component into a generic mixin more complicated because I have to re-write all method calls that I am moving. The problem here being that I use two radically different ways to call a method depending on where it is defined.

Also when I define a function somewhere, I expect to deal with the Function object when calling it. How can I compose mixins methods in a functional way, eg `_.throttle(this.toogle, 100);`? How can I `apply` some arguments? The more frequent usage of a function object is to call it, and in this case the  `callFirstWith` method works, but I may also want to do other things with a function.

In my very personal case the fact that I have to use `callFirstWith` to call mixin methods, made me less inclined to use mixins (in the few days I have been using blaze-components). I don't claim other will react in the same way, but I think the only fact that the `callFirstWith` API is unique in our meteor/JavaScript ecosystem should encourage us to find a more natural alternative.

**Comment by bensmeets** [comment] 2015-04-26 23:37
+1 For mquandelle's position.

**Comment by mquandalle** [comment] 2015-04-28 08:41
Putting mixins methods in the component prototype is also the approach @arunoda took for Flow components, see https://github.com/meteorhacks/flow-components#extending-components-with-mixins.

**Comment by bensmeets** [comment] 2015-04-28 08:55
I'm way out of my league, but just trying to add some thoughts. Isn't this just a matter of syntax sugar? In the sense that it's much easier for the outside world to think about mixins as adding to the prototype but under water fallback to callFirstWith?

Meaning, as an end user, I just call "this.functionNameThatCanBeDefinedAnywhereInTheChain()", under water you check if it is set directly on the "class" itself. If it is not, automatically call "this.callFirstWith(this, 'functionNameThatCanBeDefinedAnywhereInTheChain');

**Comment by mitar** [comment] 2015-04-28 08:57
The issue is that JavaScript does not provide getters or something like that. Then you could simply intercept such a call and do automatic propagation. But now you have to **modify** the prototype, which is in my opinion ugly.

**Comment by rclai** [comment] 2015-04-28 12:36
[JavaScript does have getter/setter functionality](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects#Defining_getters_and_setters). It's just not cross-browser compatible.

**Comment by mitar** [comment] 2015-04-28 12:37
It has something like [`__getattr__`](https://docs.python.org/2/reference/datamodel.html#object.__getattr__)?

**Comment by rclai** [comment] 2015-04-28 12:39
I don't know about that.

**Comment by bensmeets** [comment] 2015-04-28 12:39
Mozilla has it, but it's not under consideration for standards https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/noSuchMethod

**Comment by mitar** [comment] 2015-04-28 12:39
And is `defineProperty` something one would use this days? [Support in browsers](https://kangax.github.io/compat-table/es5/#Object.defineProperty).

**Comment by mitar** [comment] 2015-04-28 12:40
Huh, this is interesting: [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy). Is there a polyfill for this? :-)

**Comment by rclai** [comment] 2015-04-28 12:42
That is very interesting.

**Comment by rclai** [comment] 2015-04-28 12:43
Here's a [polyfill for Proxy](https://github.com/tvcutsem/harmony-reflect).

**Comment by mitar** [comment] 2015-04-28 12:43
> Due to the limitations of ES5, Proxies cannot be transpiled or polyfilled. See support from various JavaScript engines.

https://kangax.github.io/compat-table/es6/#Proxy

**Comment by mitar** [comment] 2015-04-28 12:49
It seems that polyfill just patches the existing Proxy implementation to be according to the spec, but you need some initial support for it in the browser first?

**Comment by mitar** [comment] 2015-04-28 12:53
Just to report what I am currently thinking. I do not think I want to add overriding of component by default. It just does not feel right.

But I do think that it is maybe a time to start offering "official" mixins one can use. So how would you feel if this behavior would be a mixin which would, if included, modify the component so that it calls mixins automatically?

And we could have two implementations. One which modifies the component's prototype. Another which uses Proxy.

The question I have is: would you like just to blindly copy any method to the component from mixins, or should mixin define a list of methods which it wants to attach to the component? Probably we can make it so that this is configurable with default being everything?

**Comment by mitar** [comment] 2015-04-28 13:03
> he more frequent usage of a function object is to call it, and in this case the callFirstWith method works, but I may also want to do other things with a function.

Then you use `getFirstWith`? `_.throttle(this.getFirstWith(this, 'toggle').toggle, 100);`

**Comment by bensmeets** [comment] 2015-04-28 20:49
Just adding this here, since it might be usefull for the discussion. I have the 'onRendered' on a component that has mixins, but need something that is provided in the 'onRendered' in one of the mixins. Calling super() doesn't help in this situation since it's not extending the mixin. Haven't found out how to call the mixin's 'onRendered' yet.

```
FirstMixin = BlazeComponent.extendComponent({
  onRendered: function() {
    console.log('this should be called before or during the onRendered of any comp i am mixed-in');
  }
});

Component = BlazeComponent.extendComponent({
  mixins: function () {
    return [FirstMixin];
  },
  onRendered: function() {
    console.log('component that needs info set in the onRendered of one of my mixins');
  }
});
```

Update: Worked around it by dropping the Mixins, I just use Inheritance all the way now. That causes the FirstMixin's (in this example, but not a real Mixin anymore) onRendered to be called before the Component's onRendered.

**Comment by mitar** [comment] 2015-04-28 22:32
Mixin's `onRendered` should be called automatically when a component where mixin is used is rendered. From [documentation](https://github.com/peerlibrary/meteor-blaze-components#user-content-reference_instance_onRendered):

> When mixins provide onRendered method, they are called after the component in mixins order automatically.

If this is not so, it is a bug and please provide a reproduction.

**Comment by bensmeets** [comment] 2015-04-28 22:36
Saw it, it works as designed. It's just in my case I had to access something in the component, which is set in the Mixin (so doesn't exist yet when needed). Can I ask why the Mixin's onRendered run later, just to get a better understanding of the concepts?

**Comment by mitar** [comment] 2015-04-28 22:45
> It's just in my case I had to access something in the component, which is set in the Mixin (so doesn't exist yet when needed).

How it does not yet exist? I do not understand that? You mean you need mixin's `onRendered` to add something to the component, so that component's `onRendered` can access it?

So this is just how you structure your code. You could move what you have in component's `onRendered` into another mixin after your mixin. So `onRendered` are called in the order just so that you can decide when you want to do something. If you want to do something after `onRendered` of one mixin, then make another mixin and put it behind that mixin.

Also, you do not have to put all logic into component's `onRendered`. You could create `mixinOnRendered` and then call that from your mixin `onRendered`. So:

``` coffee
# Mixin.
onRendered: ->
  @mixinParent().mixinOnRendered()
```

`mixinOnRendered` could be named in any other more semantic name, whatever you want component to do when it is rendered. If you are saying that component's `onRendered` needs some data from the mixin, then make this an explicit API mixin calls, and when it calls something on the component, just then react. And simply not on `onRendered` on the component.

You can create any API you want to expose between your component and mixins. In general component's methods should be used only for more simple components. But if you want to control the exact order of stuff, you should create a set of mixins you use, or create a set of methods you want to use to talk between mixins and the component.

**Comment by bensmeets** [comment] 2015-04-28 22:52
True, thanks for the sanity check. I was hooked on the Mixins using onRendered since it needed the DOM to do the action within it's onRendered. But forgot there is nothing that's prohibiting me from calling it manually from within the _component's_ onRendered.

**Comment by rclai** [comment] 2015-04-30 14:52
I think [this comment](https://github.com/peerlibrary/meteor-blaze-components/issues/34#issuecomment-95883702) is a valid point and the solution provided there is not too bad.

**Comment by bensmeets** [comment] 2015-04-30 14:56
I like the part of this choice being an opt-in through mixins.

**Comment by mquandalle** [comment] 2015-05-02 14:24
I this [this article](https://javascriptweblog.wordpress.com/2011/05/31/a-fresh-look-at-javascript-mixins/) is an interesting read on the “JavaScript mixins” topic.

**Comment by mitar** [comment] 2015-05-03 21:41
@mquandalle, this sounds interesting as well. But I am really reluctant to force any of those approaches as official approach. I can imagine somebody later on coming and claiming how some other approach should be used instead.

I think what could be interesting is to try to create components mixins which would allow you to wrap any of the mixins you want. For example, from the article you linked to last, we could have a mixin which you would call like:

``` coffee
mixins: ->
  [new MixinProxy asOval, {growBy: 2, shrinkBy: 2}]
```

And `MixinProxy` could be defined as:

``` coffee
MixinProxy extends BlazeComponent
  constructor: (@proxy, @options) ->

  mixinParent: (mixinParent) ->
    @proxy.call mixinParent.prototype, @options if mixinParent
    super
```

That would be then the same as:

```
asOval.call(OvalButton.prototype, {growBy: 2, shrinkBy: 2});
```

**Comment by mquandalle** [comment] 2015-05-05 18:42
One point here is that with `getFirstWith` you are basically re-implementing the same logic as the prototype chain logic (or is there anything different?). So instead of duplicating this logic, it may makes sense to add mixins in the component prototype chain (and not to merge all method directly in the component prototype).

**Comment by mitar** [comment] 2015-05-06 02:38
OK, I really do not want to fell here like I am too stubborn, but I am just trying to explain the rationale behind all this. I thought about this before made this mixins. The issue is in fact exactly that the prototype chain can be only one. There is no support for multiple inheritance.

So one could try to mingle with the prototype chain and insert mixins in some serialization order. But that would mean that I would have to decide for a particular order and only that order would be possible. And that order would also interfere with class inheritance.

So if I have a class A extending from class B, and I also want to add mixin M1 extending from M2. What would be the prototype chain? A <- B <- M1 <- M2? Or A <- M1 <- M2 <- B?

This is a bit different than multiple inheritance problem. So it is unclear what order should be made.

Also, with `super` then you have only one way to move, just up the chain.

This is why I decided for mixins to add another dimension to traditional JavaScript prototype chain. I see prototype chain as moving up and down, `super` goes up. And mixins going left and right, `getFirstWith` going to the right. (See [the diagram here](https://github.com/peerlibrary/meteor-blaze-components#mixins) to easier understand what I am talking here.)

Also, mixins get their own instance, so their own state. With this you minimize possible namespace collisions.

I agree that there could be more tight mixin implementations, which modify component prototype, or inject themselves into the component prototype chain, but I was unwilling to enforce this on the community. So I decided for a more light-weight approach, less intrusive, but which still allows you to do any of the wanted implementations.

As I said, maybe I should really just provide them, you can create a mixin which goes over all mixins and copies all methods from all other mixins onto a component. Or you can create it so that it inserts it into a prototype chain. Community can still develop mixins as it does, and then you can use a mixin to inject community mixins into your component in alternative ways.

But I do not think that we should force the whole community to have components modified under the hood.

Maybe I am just coming from a different world. Our components have often more than 30 properties on them, many fields, some coming from the database. Adding now all mixins to this mix just gets really scary. This is also one reason why maybe I made a bit more verbose method names. To minimize possible namespace conflicts.

So as I said, maybe it is just the problem that those alternative mixins and base component classes are too abstract here. But Blaze Components are really just a base. A common denominator. You should be encouraged to create your own base class. Even I am using base class for all my components which extend Blaze Components and add a lot of crazy stuff on top.

(There is even [base components](https://github.com/peerlibrary/meteor-base-component), with even smaller common denominator.)

The main goal here is reusability across the community. For that for me means keeping a basic set of features which are needed. And until now I think that all points you brought up can be implemented without having to change this basic set of features.

For example. I am not sure if it is really good that mixins extend `BlazeComponent`. Because calling all the time `@mixinParent().$('.foobar')` gets a bit tedious. One can imagine an alternative `MixinBase` class which maps `@$` to `@mixinParent().$`.

But should that be officially provided? Maybe? But probably more like an extra package you can use, or you can use your own variation.

I know that many people like-ready made solutions. Provide packages with best practices. But I do not yet know what are best practices here. So I would first like to see few packages providing few alternative mixin base classes, few alternative mixins which inject into a component in  various ways. And then we can see what works and what does not. And then we can maybe make something of that "official". If it would even be need for that.

So while I am not so eager to modify the code directly, I would love to link to such packages from the README. Or [components explorer](http://components-explorer.meteor.com/) and similar sites.

But until you show me that something cannot be done with this (I admit conservative, but still around 40 methods large) API, I am a bit reluctant to modify it in an opinionated way. Until now I think I pointed out that you can make a mixin which you can add to your component which modifies the component in any way you personally prefer. What is wrong with this approach? It still allows community to develop mixins which are interoperable. And you can call them in the way you want them?

**Comment by mitar** [comment] 2015-10-12 23:51
I think I will create a repository of various mixins as this so that people will be able to use them.

**Closed as completed by mitar** 2015-10-12 23:51 UTC
Labels: duplicate, discussion
