### ISSUE TITLE
@index not working

### ISSUE THREAD

**Issue by matteodem** [peerlibrary/meteor-blaze-components#109] opened 2015-12-23 21:48 UTC
Reproduce by doing following:
- Go to client/templates/app-body.html and add  `{{@index}}` on line 38
- See on site that index is being output
- Add `peerlibrary:blaze-components`
- Go back to site and the index is not being output anymore

has been reported here https://github.com/matteodem/meteor-easy-search/issues/366

**Comment by mitar** [comment] 2015-12-24 06:08
Have you updated Blaze Components to `0.15.1`, which is the latest version?

**Comment by mitar** [comment] 2015-12-24 06:10
This is duplicate of [this ticket](https://github.com/matteodem/meteor-easy-search/issues/331).

You still haven't upgraded to [Blaze Components 0.15.1](https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:components/package.js#L14).

**Closed as completed by mitar** 2015-12-24 06:10 UTC
