### ISSUE TITLE
onClick is used before actual click

### ISSUE THREAD

**Issue by chompomonim** [peerlibrary/meteor-blaze-components#115] opened 2016-02-02 13:29 UTC
``` jade
template(name="hello")
  a(href="/hello" onClick=onClick) Click me
```

``` CoffeeScript
class Hello extends BlazeComponent
  @register 'hello'

  onClick: (event) ->
    console.log 'Hello!'
    event.preventDefault()
```

Refresh the page (no clicks) and in console I can see:

```
> Hello!
> Exception in template helper: TypeError: Cannot read property 'preventDefault' of undefined
```

**Comment by rclai** [comment] 2016-02-02 14:57
Don't you need to use the event map? I don't think you can bind events like that.

**Comment by mitar** [comment] 2016-02-02 17:44
This works only with HTML templates. Jade has not been ported to them. Something like the following has to be done:

https://github.com/peerlibrary/meteor-blaze-components/blob/master/patch-compiling.js

Duplicate of #113.

> Don't you need to use the event map? I don't think you can bind events like that. 

Yes you can with recent version of Blaze Components.

**Closed as completed by mitar** 2016-02-02 17:44 UTC
Labels: duplicate
